version: '3'

services:
  web:
    restart: on-failure
    container_name: cardinalsweb
    build: ./cardinalsproject
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./cardinalsproject:/code:rw
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: cardinals.settings.development
    ports:
      - "8000:8000"
    env_file:
      - .env
    links:
    - "updater:updater"

  updater:
    container_name: updater
    build: ./updaterproject
    command: bash -c 'python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:3000'
    volumes:
      - ./updaterproject:/code:rw
    ports:
      - "3000:3000"
    env_file:
      - .env

  db:
    container_name: db
    restart: always
    image: postgres:10-alpine
    volumes:
      - ./.dbdata:/var/lib/postgresql:rw
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cardinals
      POSTGRES_PASSWORD: cardinals
      POSTGRES_DB: cardinals

networks:
  cardinals_master_default:
    external: true