version: '3'

services:
  web:
    restart: on-failure
    container_name: cardinalsweb
    build: ./cardinalsproject
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; ./run_tests.sh'
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: cardinals.settings.development
    ports:
      - "8000:8000"
    env_file:
      - .env

  db:
    container_name: db
    restart: always
    image: postgres:10-alpine
    volumes:
      - ./.dbdata:/var/lib/postgresql:rw
    ports:
      - 5432
    environment:
      POSTGRES_USER: cardinals
      POSTGRES_PASSWORD: cardinals
      POSTGRES_DB: cardinals
